# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='')),
                ('user_id', models.CharField(default='0', max_length=200)),
                ('project_id', models.IntegerField(default=0)),
                ('rev_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='deepModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='')),
                ('user_id', models.CharField(default='0', max_length=200)),
                ('project_id', models.IntegerField(default=0)),
                ('advance_layers', models.BooleanField(default=False)),
                ('imports', models.TextField(default='')),
                ('rev_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='importModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='0', max_length=200)),
                ('project_id', models.IntegerField(default=0)),
                ('file_name', models.CharField(default='', max_length=200)),
                ('compute_server', models.CharField(max_length=200)),
                ('session_id', models.CharField(max_length=32)),
                ('compute_session', models.CharField(default='NOTSET', max_length=32)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='paramsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='')),
                ('user_id', models.CharField(default='0', max_length=200)),
                ('project_id', models.IntegerField(default=0)),
                ('rev_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('train_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('session_cookie', models.CharField(default='', max_length=64)),
                ('test_data', models.CharField(default='', max_length=64)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='trainingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='0', max_length=200)),
                ('project_id', models.IntegerField(default=0)),
                ('compute_server', models.CharField(max_length=200)),
                ('compute_type', models.CharField(default='', max_length=32)),
                ('run_name', models.CharField(default='Run0', max_length=200)),
                ('run_id', models.IntegerField()),
                ('session_id', models.CharField(max_length=32)),
                ('compute_session', models.CharField(default='NOTSET', max_length=32)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
                ('load_weights', models.IntegerField(default=-1)),
                ('save_weights_on', models.CharField(default='epoch', max_length=32)),
            ],
        ),
    ]
