# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('project_id', models.IntegerField(default=0)),
                ('project_title', models.CharField(max_length=64)),
                ('project_description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('accessed_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
