# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='1', max_length=200)),
                ('project_id', models.IntegerField(default=0)),
                ('model_name', models.TextField(default='')),
                ('model_config', models.TextField(default='{}')),
                ('imports', models.TextField(default='')),
                ('config', models.TextField(default='{"inputDataType":"image", "outputDataType" : "category"')),
            ],
        ),
    ]
